"""changed image table columns

Revision ID: 014790f4145a
Revises: 342b375a37ae
Create Date: 2023-03-30 07:55:45.882722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '014790f4145a'
down_revision = '342b375a37ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('name', sa.String(), nullable=False))
    op.add_column('images', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images', 'data')
    op.drop_column('images', 'name')
    # ### end Alembic commands ###
