"""Fixed relationship in Book model again

Revision ID: 342b375a37ae
Revises: e17992ec6d7d
Create Date: 2023-03-30 03:27:00.745181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342b375a37ae'
down_revision = 'e17992ec6d7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
