"""Added column teacher in books

Revision ID: 71ca8eb9da33
Revises: 82d921c3d474
Create Date: 2023-03-30 02:34:37.106057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ca8eb9da33'
down_revision = '82d921c3d474'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('professor', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'professor')
    # ### end Alembic commands ###
