"""Fixed relationship in Book model

Revision ID: e17992ec6d7d
Revises: 75033f740793
Create Date: 2023-03-30 03:21:33.991053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17992ec6d7d'
down_revision = '75033f740793'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
