# TODO: I need to figure out a way to properly test this

# from app.db.models import Image as ImageModel
# from app.main import app

# import multipart

# from fastapi.testclient import TestClient
# from fastapi import status

# client = TestClient(app)

# This test tests the route for adding new images to a book

# def test_add_image_route(db_session, books_on_db):

#     # Using the id of a book generated by a fixture
#     response = client.post('/image/add', 
#         data={"file": ("dummy.png", "123456", "image/png"), "book_id": books_on_db[0].id}
#     )
    
#     assert response.status_code == status.HTTP_201_CREATED

#     images_on_db = db_session.query(ImageModel).all()

#     assert len(images_on_db) == 1

#     db_session.delete(images_on_db)
#     db_session.commit()