from app.db.models import Text as TextModel
from app.main import app

from fastapi.testclient import TestClient
from fastapi import status

client = TestClient(app)

# This test tests the route for adding new texts to a book

def test_add_text_route(db_session, books_on_db):

    # Using the id of a book generated by a fixture
    body = {
        "text": {
            "text": "Lorem ipsum dolor sit amet consectetur adipiscing elit. Morbi ligula magna convallis in dolor sed, feugiat sagittis ipsum."
        },
        "book_id": books_on_db[0].id
    }

    response = client.post('/text/add', json=body)

    assert response.status_code == status.HTTP_201_CREATED

    texts_on_db = db_session.query(TextModel).all()

    assert len(texts_on_db) == 1

    db_session.delete(texts_on_db[0])
    db_session.commit